on: [push, pull_request]

name: CI

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: clippy
      - name: cargo clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  test-nightly:
    name: Test (Nightly)
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set Toolcchain
        run: echo 'nightly-2021-12-04' > rust-toolchain
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features nightly


